<?xml version="1.0" encoding="utf-8"?><Database Name="ClassSRM" Class="ClassSRMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ClassSRM;Integrated Security=True" SettingsObjectName="ClassSRM.Properties.Settings" SettingsPropertyName="ClassSRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_User" Member="tbl_Users">
    <Type Name="tbl_User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ActPoint" Member="tbl_ActPoints">
    <Type Name="tbl_ActPoint" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Descr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Check" Member="tbl_Checks">
    <Type Name="tbl_Check" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_EvaPoint" Member="tbl_EvaPoints">
    <Type Name="tbl_EvaPoint" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Book" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Descr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SumEva" Member="SumEvas">
    <Type Name="SumEva" Modifier="Sealed">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Book" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Student" Member="tbl_Students">
    <Type Name="tbl_Student" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StuClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuGender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StuImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CheckV" Member="CheckVs">
    <Type Name="CheckV" Id="ID1" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Exist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_School" Member="tbl_Schools">
    <Type Name="tbl_School" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchAdmin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchDate" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Tasks" Member="tbl_Tasks">
    <Type Name="tbl_Task" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Label" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Quastion" Member="tbl_Quastions">
    <Type Name="tbl_Quastion" Modifier="Sealed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Book" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SumAE" Member="SumAEs">
    <Type Name="SumAE" Modifier="Sealed">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(304) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cars" Member="DBResources">
    <Type Name="DBResource">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Trademark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Liter" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cyl" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TransmissSpeedCount" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TransmissAutomatic" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="MPG_City" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MPG_Highway" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Hyperlink" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="RtfContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CarScheduling" Member="DBAppointments">
    <Type Name="DBAppointment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Label" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AllDay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecurrenceInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReminderInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CarIdShared" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SelectSumEvaDate" Method="SelectSumEvaDate">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date1" Parameter="date1" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Date2" Parameter="date2" Type="System.String" DbType="NVarChar(12)" />
    <ElementType Name="SelectSumEvaDateResult">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Book" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSchool" Method="SelectSchool">
    <ElementType Name="SelectSchoolResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchAdmin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchClass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SchDate" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select2Dates" Method="Select2Dates">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date1" Parameter="date1" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Date2" Parameter="date2" Type="System.String" DbType="NVarChar(12)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.UpdateTaskLabel" Method="UpdateTaskLabel">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Label" Parameter="label" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertTask" Method="InsertTask">
    <Parameter Name="Caption" Parameter="caption" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Label" Parameter="label" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteTask" Method="DeleteTask">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSchool" Method="InsertSchool">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertStudent" Method="InsertStudent">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Image" Parameter="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="HashPass" Parameter="hashPass" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertCheck" Method="InsertCheck">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertEvaBook" Method="InsertEvaBook">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Score" Parameter="score" Type="System.Int32" DbType="Int" />
    <Parameter Name="Book" Parameter="book" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertActPoint" Method="InsertActPoint">
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Score" Parameter="score" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteAllQuastion" Method="DeleteAllQuastion">
    <Parameter Name="SchId" Parameter="schId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AddQuastion" Method="AddQuastion">
    <Parameter Name="SchId" Parameter="schId" Type="System.Int32" DbType="Int" />
    <Parameter Name="StuId" Parameter="stuId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Book" Parameter="book" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectTopYear" Method="SelectTopYear">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectTopYearResult">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectTopMonth" Method="SelectTopMonth">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date1" Parameter="date1" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Date2" Parameter="date2" Type="System.String" DbType="NVarChar(12)" />
    <ElementType Name="SelectTopMonthResult">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectGifts" Method="SelectGifts">
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateMinCur" Parameter="dateMinCur" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="DateMaxCur" Parameter="dateMaxCur" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="DateMinPrev" Parameter="dateMinPrev" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="DateMaxPrev" Parameter="dateMaxPrev" Type="System.String" DbType="NVarChar(12)" />
    <ElementType Name="SelectGiftsResult">
      <Column Name="HaveGift" Type="System.String" DbType="NVarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUser" Method="UpdateUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="HashPass" Parameter="hashPass" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSchool" Method="UpdateSchool">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSchool" Method="DeleteSchool">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteStudent" Method="DeleteStudent">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateStudent" Method="UpdateStudent">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="SchoolId" Parameter="schoolId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LName" Parameter="lName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FName" Parameter="fName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Image" Parameter="image" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCheck" Method="UpdateCheck">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteCheck" Method="DeleteCheck">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteActPoint" Method="DeleteActPoint">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateActBook" Method="UpdateActBook">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Score" Parameter="score" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateEvaBook" Method="UpdateEvaBook">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="StudentId" Parameter="studentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Score" Parameter="score" Type="System.Int32" DbType="Int" />
    <Parameter Name="Book" Parameter="book" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Date" Parameter="date" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteEvaBook" Method="DeleteEvaBook">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateTask" Method="UpdateTask">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Caption" Parameter="caption" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Desc" Parameter="desc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Label" Parameter="label" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectSumEvaPoint" Method="SelectSumEvaPoint">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectSumEvaPointResult">
      <Column Name="SUMEVA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSumBook" Method="SelectSumBook">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Book" Parameter="book" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SelectSumBookResult">
      <Column Name="HighScoreUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectQActivity" Method="SelectQActivity">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectQActivityResult">
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectNOTExistCheck" Method="SelectNOTExistCheck">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectNOTExistCheckResult">
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectExistCheck" Method="SelectExistCheck">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectExistCheckResult">
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectQueryWin" Method="SelectQueryWin">
    <ElementType Name="SelectQueryWinResult">
      <Column Name="HighScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectStudentByClassId" Method="SelectStudentByClassId">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectStudentByClassIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StuClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StuName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuFName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="StuGender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StuImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectCurScore" Method="SelectCurScore">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectCurScoreResult">
      <Column Name="ScoreSum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>